#pragma once
#define _CRT_SECURE_NO_WARNINGS
#define NOMINMAX
#define pt(Victim) (Victim.X)][(Victim.Y)
#define ktn_audio_ct 4
#define ktn_border_width 4
#define ktn_buffer_size 360
#define ktn_buttons 50
#define ktn_captions 6
#define ktn_categories 8
#define ktn_channels 1
#define ktn_cmd_max 16
#define ktn_days 7
#define ktn_degree "\u00b0"
#define ktn_dock_cap 750.0
#define ktn_effects 2
#define ktn_epsilon 1e-7
#define ktn_errors 13
#define ktn_facts 7
#define ktn_fish 3
#define ktn_fish_phases 6
#define ktn_fonts 7
#define ktn_grid_size 48
#define ktn_hx_cap 1200
#define ktn_hx_efficiency 1200
#define ktn_invalid -1
#define ktn_json_max 8
#define ktn_keybinds 14
#define ktn_large_cap 150
#define ktn_log_max 11
#define ktn_logs 3
#define ktn_ocean_size 1024
#define ktn_param_max 128
#define ktn_perm_buttons 2
#define ktn_quirks 4
#define ktn_recipe_types 3
#define ktn_reinforced_cap 30
#define ktn_room_temp 65
#define ktn_savefiles 4
#define ktn_scalar_max 6
#define ktn_sliders 15
#define ktn_static_rate 15
#define ktn_sub_speed 4
#define ktn_subcategories 6
#define ktn_suffixes 5
#define ktn_supported_res 6
#define ktn_terminator -105
#define ktn_tile_size 40
#define ktn_tools 5
#define ktn_turbine_coefficient 0.15
#define ktn_unit "uFI"
#define ktn_valve300_len 12
#define ktn_water_boil_pt 211.3