#pragma once
#define _USE_MATH_DEFINES
#include <math.h>
#include <miniaudio/miniaudio.h>
#include <SDL3/SDL.h>
#include <SDL3_ttf/SDL_ttf.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <stdint.h>
#include <signal.h>
#include <setjmp.h>
#include <string.h>
#include <fcntl.h>
#include <ctype.h>
#include <time.h>
#include <unistd.h>