#pragma once
#include <miniaudio/miniaudio.h>
#include <SDL3/SDL.h>
#include <freetype/freetype.h>
#include <corecrt_math_defines.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <stdint.h>
#include <ctype.h>
#include <setjmp.h>
#include <time.h>
#include <threads.h>