#pragma once
#define free_c(Victim) do { if ((Victim) != NULL) { free(Victim); (Victim) = NULL; } } while(0)
#define intlen(Victim) ({ int Yield = 0; while ((Victim)[Yield] != LDE_TERMINATOR) { Yield++; } Yield; })
#define reclen(Victim) ({ int Yield = 0; while ((Victim)[Yield].ID != LDE_TERMINATOR) { Yield++; } Yield; })
#define ptlen(Victim) ({ int Yield = 0; while ((Victim)[Yield].X != LDE_TERMINATOR || (Victim)[Yield].Y != LDE_TERMINATOR) { Yield++; } Yield; })
#define veclen(Victim) ({ int Yield = 0; while (strcmp((Victim)[Yield], NULLSTRING) != 0) { Yield++; } Yield; })
#define clamp_c(Victim, A, B) ({ int Yield = (Victim); if ((A) < (B)) { if ((Victim) < (A)) { Yield = (A); } else if ((Victim) > (B)) { Yield = (B); } } else { if ((Victim) < (B)) { Yield = (B); } else if ((Victim) > (A)) { Yield = (A); } } Yield; })
#define charcat(Victim, A) do { int Length = strlen(Victim); (Victim)[Length] = (A); (Victim)[Length + 1] = '\0'; } while(0)
#define step_c(Victim) do { (Victim) = ((Victim) * 2891336453u) + 747796405u; (Victim) ^= (Victim) >> 16; } while(0)
#define free_texture(Victim) do { if (Victim != NULL) { SDL_DestroyTexture(Victim); Victim = NULL; } } while(0)