#pragma once
#include <core.h>
#include <buttons.h>

struct Proto_Core {
	SDL_Window* Window;
	SDL_Renderer* Renderer;
	SDL_Texture* Game_Texture;
	bool Is_Running;
	bool Debug_Mode;
	char Suffixes[ktn_suffixes];
	float Save_Filesizes[4];
	int Selected_Save;
	Point_f Camera;
	Point_f Mouse;
	Point_f Screensize;
	Point_f Screenhalfsize;
	int Machines;
	int Items;
	int Recipes;
	int Fishes;
	int Genes;
	int Perks;
	int Categories;
	int Subcategories;
	int Tile_Size;
	int Buffer_Size;
	float Ratio;
	uint32_t State;
};

struct Proto_Data {
	bool CMD_Placed;
	bool Help_Clicked;
	int Version;
	int Time;
	int Day;
	char Visual_Grid[ktn_grid_size][ktn_grid_size][64];
	int32_t Behavior_Grid[ktn_grid_size][ktn_grid_size];
	int32_t Wiring_Grid[ktn_grid_size][ktn_grid_size];
	int32_t Plumbing_Grid[ktn_grid_size][ktn_grid_size];
	char Items_Grid[ktn_grid_size][ktn_grid_size][64];
	int32_t Temperature_Grid[ktn_grid_size][ktn_grid_size];
	float Animation_Grid[ktn_grid_size][ktn_grid_size][3];
	float Data_Grid[ktn_grid_size][ktn_grid_size][7];
	float Settings_Grid[ktn_grid_size][ktn_grid_size][16];
	char Processing_Grid[ktn_grid_size][ktn_grid_size][64];
	int64_t Funds;
};

struct Proto_Metadata {
	char Monitor_Size[64];
	char* Buttons[ktn_buttons];
	char* Logs[ktn_logs];
	char*** Contents;
	char*** Subcontents;
	const char* Days[ktn_days];
	const Point Supported_Resolutions[ktn_supported_res];
	const char Tool_Texts[ktn_tools][64];
	Machine_Data* Machines;
	Item_Data* Items;
	Fish_Data* Fish;
	Gene_Data* Genes;
	Perk_Data* Perks;
	Category_Data* Categories;
	Category_Data* Subcategories;
	Recipe* Recipes;
	Item_Data Null_Item;
};

struct Proto_Settings {
	bool AA_Temporary;
	bool VS_Temporary;
	int Fullscreen;
	int Scalar;
	int Anti_Aliasing;
	int VSync;
	int Volume;
	int Raw_FPS;
};

struct Proto_Textures {
	SDL_Texture* Logo;
	SDL_Texture* Terminal_Prompt;
	SDL_Texture* Price_Header;
	SDL_Texture* CMD_Warning1;
	SDL_Texture* CMD_Warning2;
	Texture3_Array Item_Labels;
	Texture3_Array Subcategories;
	Texture3_Array Subcontents;
	Texture2_Array New;
	Texture2_Array Load;
	Texture2_Array Clear;
	Texture2_Array Categories;
	Texture_Array Error_Exit;
	Texture2_Array MSP_Buttons;
	Texture2_Array SD_Buttons;
	Texture2_Array HX_Buttons;
	Texture2_Array TT_Buttons;
	Texture2_Array MT_Buttons;
	Texture_Array Arrow;
	Texture_Array S_Dock;
	Texture_Array Tunnel;
	Texture_Array Return;
	Texture_Array New_Game;
	Texture_Array Settings;
	Texture_Array Update_Logs;
	Texture_Array Credits;
	Texture_Array Quit_Game;
	Texture_Array Apply;
	Texture_Array Cancel;
	Texture_Array Next_Day;
	Texture_Array Cap;
	Texture2_Array Anti_Aliasing;
	Texture2_Array V_Sync;
	Texture2_Array Sort;
	Texture2_Array TBW_Texture;
	Texture_Array Quirk;
	Texture_Array Quirk_Label;
	Texture2_Array Tutorials;
	Texture2_Array Cheats;
	Texture_Array Clear_Tutorial;
	Texture_Array Settings_Label;
	Texture_Array Save_Settings;
	Texture_Array Tool;
	Texture_Array Help_Content;
	SDL_Texture* Recipe_Content;
	SDL_Texture* Genetics_Content;
	SDL_Texture* Perks_Content;
	SDL_Texture* Time_Content;
	Texture_Array Door;
	SDL_Texture* Emblem;
	SDL_Texture* Crosshair;
	SDL_Texture* Cursor;
	SDL_Texture* Cursor_Core;
	SDL_Texture* Sapling;
	SDL_Texture* Node;
	SDL_Texture* Path_Arrow;
	SDL_Texture* Log_Background;
	SDL_Texture* Saveloader;
	SDL_Texture* Genetics;
	SDL_Texture* R_Flash;
	Texture_Array A_Bubble;
	SDL_Texture* Floor_Texture;
	SDL_Texture* Frame_Texture;
	SDL_Texture* Gene_Added;
	SDL_Texture* Perk_Owned;
	SDL_Texture* Tile_Texture;
	SDL_Texture* Scrap;
	SDL_Texture* Help_Sidebutton;
	SDL_Texture* Save_Sidebutton;
	SDL_Texture* Recipe_Sidebutton;
	SDL_Texture* Genetics_Sidebutton;
	SDL_Texture* Perks_Sidebutton;
	SDL_Texture* Time_Sidebutton;
	SDL_Texture* Exit_Sidebutton;
	Texture_Array Submarine;
	Texture2_Array Confirmation;
	Texture_Array Pyramid;
	Texture_Array Fire;
	Texture_Array None;
	SDL_Texture* Subarrow;
};

struct Proto_Rects {
	SDL_FRect Logo;
	SDL_FRect Terminal_Prompt;
	SDL_FRect Price_Header;
	SDL_FRect CMD_Warning1;
	SDL_FRect CMD_Warning2;
	Rect3_Array Item_Labels;
	Rect3_Array Subcategories;
	Rect3_Array Subcontents;
	Rect2_Array New;
	Rect2_Array Load;
	Rect2_Array Clear;
	Rect2_Array Categories;
	Rect_Array Error_Exit;
	Rect2_Array MSP_Buttons;
	Rect2_Array SD_Buttons;
	Rect2_Array HX_Buttons;
	Rect2_Array MT_Buttons;
	Rect2_Array TT_Buttons;
	Rect_Array Tunnel;
	Rect_Array Return;
	Rect_Array New_Game;
	Rect_Array Settings;
	Rect_Array Update_Logs;
	Rect_Array Credits;
	Rect_Array Quit_Game;
	Rect_Array Apply;
	Rect_Array Cancel;
	Rect_Array Next_Day;
	Rect2_Array Anti_Aliasing;
	Rect2_Array V_Sync;
	Rect2_Array Sort;
	Rect2_Array TBW_Rectangle;
	Rect2_Array Tutorials;
	Rect2_Array Cheats;
	Rect_Array Clear_Tutorial;
	Rect_Array Settings_Label;
	Rect_Array Save_Settings;
	SDL_FRect Tool[ktn_tools];
	SDL_FRect Help_Content[2];
	SDL_FRect Recipe_Content;
	SDL_FRect Genetics_Content;
	SDL_FRect Perks_Content;
	SDL_FRect Time_Content;
	SDL_FRect Door[2];
	SDL_FRect Emblem;
	SDL_FRect Tile_1x1;
	SDL_FRect Tile_2x2;
	SDL_FRect Tile_2x3;
	SDL_FRect Tile_3x2;
	SDL_FRect Tile_3x3;
	SDL_FRect Tile_6x4;
	SDL_FRect Node;
	SDL_FRect R_Flash;
	SDL_FRect Log_Background;
	SDL_FRect Saveloader;
	SDL_FRect Help;
	SDL_FRect Save;
	SDL_FRect Recipe;
	SDL_FRect Genetics;
	SDL_FRect Perks;
	SDL_FRect Time;
	SDL_FRect Exit;
	SDL_FRect Submarine;
	Rect2_Array Confirmation;
	SDL_FRect Subarrow;
};

struct Proto_Colors {
	SDL_Color Abyss_Black;
	SDL_Color Pure_White;
	SDL_Color Light_Grey;
	SDL_Color Mid_Grey;
	SDL_Color Clean_Grey;
	SDL_Color Dark_Grey;
	SDL_Color Reinforced_Grey;
	SDL_Color Cherry_Blossom;
	SDL_Color Copper_Wire;
	SDL_Color Carnage_Pink;
	SDL_Color Hostile_Red;
	SDL_Color Ocean;
	SDL_Color Base_Pair[4];
};

struct Proto_Fonts {
	TTF_Font* Faces[ktn_fonts];
	const char* Paths[ktn_fonts];
	const int Sizes[ktn_fonts];
};

struct Proto_Keybinds {
	char* Keybind_Texts[ktn_keybinds];
	SDL_Keycode Keybind_List[ktn_keybinds];
	SDL_Keycode Keybind_Settings[ktn_keybinds];
};

struct Proto_Temporary {
	bool Settings_Changed;
	int Modular1_Requirement;
	int Modular2_Requirement;
	int Ticker_Target;
	int Ticker_Position;
	int Ticker_Frames;
	int Tutorial_Step;
	Point Tutorial_Size;
	Point Tutorial_Offset;
	char Tutorial_Selection[64];
	int Temporary_FPS;
	float Scroll_Percent;
	bool Log_Inversions[3];
	Point First_Coordinate;
	Node_d Docks;
	SDL_Texture* Lighting[4];
	int Pixels;
	SDL_Texture* Spinner;
	SDL_FRect Spinner_Rect;
	SDL_Texture* Load_Text;
	SDL_FRect Load_Text_Rect;
};

struct Proto_Cache {
	int Wire_State;
	Texture_Array Wire_Cache;
	SDL_FRect Wire_Box;
	SDL_Texture* Light_Grad;
	SDL_Texture* Blueprint_Cache;
	SDL_FRect Query[64];
	int ID_Query[64];
	SDL_Color Color_Query[64];
	int Query_Length;
	float* FPS_Cache;
	int FPS_Tick;
};

struct Proto_Supplies {
	Texture_Supply FPS;
	Texture_Supply Scroll_Percent;
	Texture_Supply Changelog_Scroll;
	Texture_Supply Report_Header;
	Texture_Supply Monitor_Size;
	Texture_Supply Tutorial;
	Texture_Supply Subtutorial;
	Texture_Supply Money_Production;
	Texture_Supply Fluid_Production;
	Texture_Supply Power_Production;
	Texture_Supply Shop1;
	Texture_Supply Shop2;
	Texture_Supply Shop3;
	Texture_Supply Shop4;
	Texture_Supply Shop5;
	Texture_Supply Save_Text;
	Texture_Supply Terminal_Title;
	Texture_Supply Terminal_Command;
	Texture_Supply Terminal_Logs[ktn_log_max];
	Texture_Supply Catalog1[ktn_recipe_types];
	Texture_Supply Catalog2[ktn_recipe_types];
	Texture_Supply Catalog3[ktn_recipe_types];
	Texture_Supply Filesizes[ktn_savefiles];
};

struct Proto_Interface {
	bool Locked;
	bool Building;
	bool Sprinting;
	float Ocean_Cycle;
	float Node_Cycle;
	float Movespeed;
	float Log_Offset;
	Point Tile;
	int Prompt_Identifier;
	int Subprompt_Identifier;
	int Tool;
	int UD_Input;
	int LR_Input;
	int Queried_Price;
	int Engagement;
	Point Looper;
	int UI_Tab;
	int Subtab;
	UI_Link UI_Query;
	int Frame_Rate;
	int Time_Frames;
	int Max_Time_Frames;
	Machine_Ptr Item;
	int Rotation;
	int Save_Frames;
	int Map_X;
	int Map_Y;
	int Registering_Keybind;
	int Slider_Positions[ktn_sliders];
	SDL_FPoint Tile_Centerpoint;
	float Log_Heights[ktn_logs];
	int Valve300_Postions[ktn_valve300_len];
	float Time_Positions[ktn_time_len];
	char Slider_Texts[ktn_sliders][256][64];
	float Effects[ktn_effects];
	char Terminal_Logs[ktn_log_max][ktn_param_max];
	char Terminal_Entry[128];
	int Terminal_Length;
	bool Bar_Up;
};

struct Proto_Buffers {
	char JSON[ktn_json_max][128];
	int Commands[ktn_cmd_max];
	char Parameters[ktn_cmd_max][4][ktn_param_max];
};

extern struct Proto_Core Core;
extern struct Proto_Data Data;
extern struct Proto_Metadata Metadata;
extern struct Proto_Settings Settings;
extern struct Proto_Textures Textures;
extern struct Proto_Rects Rects;
extern const struct Proto_Colors Colors;
extern struct Proto_Fonts Fonts;
extern struct Proto_Keybinds Keybinds;
extern struct Proto_Temporary Temporary;
extern struct Proto_Cache Cache;
extern struct Proto_Supplies Supplies;
extern struct Proto_Interface Interface;
extern struct Proto_Buffers Buffers;

void Preload_Fonts();
int Visual_To_Rotation(const char* Identifier);
Machine_Ptr Get_Machine(const char* Index);
Machine_Ptr Visual_To_Machine(const char* Identifier);
void ID_To_Size(Machine_Ptr Machine, const int Rotation, int* W, int* H);
void Clear_Renderer();
void Set_Renderer_Color(const SDL_Color Color);
void Cleanup_Assets();
void Clear_File(const char* Path);
void Free_String2(String2* Target);
void Clear_Texture_Array(Texture_Array* Target);
void Clear_Texture2_Array(Texture2_Array* Target);
void Clear_Texture3_Array(Texture3_Array* Target);
void Clear_Rect2_Array(Rect2_Array* Target);
void Clear_Rect3_Array(Rect3_Array* Target);
int Get_Depth(float Number);
void Render_Outline(SDL_FRect Rectangle, SDL_Color Color, int Multiplier);
void Render_Box(Point Pos, int W, int H, SDL_Color Inner_Color, SDL_Color Outer_Color);
bool Render_Button(const Texture_Array* Button, const Rect_Array* Hitbox, UI_Link Link, SDL_Color Underline_Color);
void Preload_Assets();
void Update_Tilestack(bool X_Lock, int X, bool Y_Lock, int Y);
bool Detect_Mouse_Collision(const SDL_FRect Target);
bool Is_Bound(Point Input);
bool Compare_Colors(const SDL_Color Color1, const SDL_Color Color2);
bool Check_Clearance(Point Pos, const int W, const int H);
void Fill_Clearance(const char* Identifier, Point Pos, const int W, const int H);
void Push_Docks(Point Input);
void Pull_Docks(int Position);
void Recache_TT_Commands();
void Preload_Terminal_Sidebar(const String2* Texts, Texture2_Array* Yield, Rect2_Array* Rectangles);
void Load_Button(Font_Index Font, const char* Text, Texture_Array* Yield, Rect_Array Rectangles, SDL_Color Color1, SDL_Color Color2);
SDL_FRect Buffer_Rectangle(const SDL_FRect Source, Point Pos);
void Bake_Lights();
void Load_Modular(const char* Path, Texture_Array* Yield, int Size);
void Load_Rotational(const char* Path, Texture_Array* Yield);
void Load_Mirrored_Button(const char* Path, Texture2_Array* Yield, SDL_FRect* Rectangle);
void Load_Mirrored(const char* Path, Texture_Array* Yield,  SDL_FRect* Rectangle);
void Load_Animated(const char* Path, Texture_Array* Yield, int Height, bool Inverted);
void Load_Subanimated(const char* Path, Texture_Array* Yield, int Height);
void Load_Animated_Rotational(const char* Path, Texture2_Array* Yield, int Height, bool Inverted);
SDL_Texture* Preload_Sidebutton(const char* Path, SDL_FRect* Rectangle, float Y);
SDL_Texture* Preload_Texture(const char* Path);
void Abbreviate_Number(float Number, char* Buffer, int Size);
void Truncate(float Number, int Depth, char* Buffer, int Size);
int Render_Rich_Text(Font_Index Font, char* Raw_Text, Point Pos, bool Inverted, bool Disabled);
void Render_Texture(SDL_Texture* Texture, SDL_FRect* Rect);
void Preload_Noise();
void Preload_Lights();
void Preclear_Temporaries();
void Render_Loadscreen(const char* Line);
void Reseed_State();
SDL_FRect Inline_Rect(SDL_FRect Input, const int Border);
SDL_Texture* Render_Text(Font_Index Font, const char* Text, SDL_Color Color);
SDL_Texture* New_Texture(int Width, int Height);
SDL_Texture* Surface_To_Texture(SDL_Surface* Surface);
SDL_Texture* IMG_To_Texture(const char* Path);
void Load_XML();
char* Find_Element(const char* Path, const char* Text, const char* Element, int* End_Yield);
char** Find_Multiple(const char* Path, const char* Text, const char* Element, int Count);
bool Load_Text();
void Free_Text();
Point Rotate_Pt(Point Input, Point Size, int Rot);
Point Rotate_Px(Point Input, Point Size, int Rot);
Category_Ptr Get_Category(const char* Index);
void Update_Cursor();
void Sell(Point Pos, bool Terminal);
Perk_Ptr Get_Perk(const char* Index);
void Load_Rects();