#pragma once
#include <core.h>

typedef struct {
	SDL_Window* Window;
	SDL_Renderer* Renderer;
	SDL_Texture* Game_Texture;
	bool Is_Running;
	bool Debug_Mode;
	char Suffixes[LDE_SUFFIXES];
	float Save_Filesizes[4];
	int Selected_Save;
	Point_f Camera;
	Point_f Mouse;
	uint32_t State;
} lde_core;

typedef struct {
	bool CMD_Placed;
	int Version;
	int Time;
	int Day;
	int Visual_Grid[LDE_GRIDSIZE][LDE_GRIDSIZE];
	int Behavior_Grid[LDE_GRIDSIZE][LDE_GRIDSIZE];
	int Wiring_Grid[LDE_GRIDSIZE][LDE_GRIDSIZE];
	int Plumbing_Grid[LDE_GRIDSIZE][LDE_GRIDSIZE];
	int Items_Grid[LDE_GRIDSIZE][LDE_GRIDSIZE];
	int Temperature_Grid[LDE_GRIDSIZE][LDE_GRIDSIZE];
	float Animation_Grid[LDE_GRIDSIZE][LDE_GRIDSIZE][3];
	float Data_Grid[LDE_GRIDSIZE][LDE_GRIDSIZE][7];
	float Settings_Grid[LDE_GRIDSIZE][LDE_GRIDSIZE][16];
	int64_t Funds;
} lde_data;

typedef struct {
	char Monitor_Size[64];
	char* Names[LDE_MACHINES];
	char* Descriptions[LDE_MACHINES];
	char* Categories[LDE_CATEGORIES];
	char* Subcategories[LDE_SUBCATEGORIES];
	char* Buttons[LDE_BUTTONS];
	SDL_Texture* Machine_Sprites[LDE_MACHINES];
	SDL_FRect Machine_Rectangles[LDE_MACHINES];
	int Subcategory_Positions[LDE_CATEGORIES][8];
	int Item_Labels[LDE_CATEGORIES][16];
	int Subcontents[LDE_SUBCATEGORIES][16];
	int Machine_Taxes[LDE_MACHINES];
	int Machine_Prices[LDE_MACHINES];
	char* Logs[LDE_LOGS];
	int* Heating_Machines;
	int* Irradiating_Machines;
	int Quirk_Positions[LDE_QUIRKS][64];
	bool Machine_Quirks[LDE_MACHINES][LDE_QUIRKS];
	const char* Days[LDE_DAYS];
	const Point Supported_Resolutions[LDE_SUPPORTEDRESOLUTIONS];
	char* Facts[LDE_FACTS];
	const char Tool_Texts[LDE_TOOLS][64];
} lde_metadata;

typedef struct {
	bool AA_Temporary;
	bool VS_Temporary;
	int Fullscreen;
	int Screen_Size;
	int Anti_Aliasing;
	int VSync;
	int Volume;
	int Raw_FPS;
} lde_settings;

typedef struct {
	SDL_Texture* Logo1;
	SDL_Texture* Logo2;
	SDL_Texture* Terminal_Prompt;
	SDL_Texture* Price_Header;
	SDL_Texture* CMD_Warning1;
	SDL_Texture* CMD_Warning2;
	Texture3_Array Item_Labels;
	Texture3_Array Subcategories;
	Texture3_Array Subcontents;
	Texture2_Array New;
	Texture2_Array Load;
	Texture2_Array Clear;
	Texture2_Array Categories;
	Texture_Array Error_Exit;
	Texture2_Array MSP_Buttons;
	Texture2_Array SD_Buttons;
	Texture2_Array HX_Buttons;
	Texture2_Array TT_Buttons;
	Texture2_Array MT_Buttons;
	Texture_Array R_Pipe;
	Texture_Array L_Pipe;
	Texture_Array MS_Pool;
	Texture_Array Arrow;
	Texture_Array S_Dock;
	Texture_Array Tunnel;
	Texture_Array Return;
	Texture_Array New_Game;
	Texture_Array Settings;
	Texture_Array Update_Logs;
	Texture_Array Credits;
	Texture_Array Quit_Game;
	Texture_Array Apply;
	Texture_Array Cancel;
	Texture_Array Next_Day;
	Texture_Array Cap;
	Texture2_Array Anti_Aliasing;
	Texture2_Array V_Sync;
	Texture2_Array Sort;
	Texture2_Array TBW_Texture;
	Texture_Array Quirk;
	Texture_Array Quirk_Label;
	Texture2_Array Tutorials;
	Texture2_Array Cheats;
	Texture_Array Clear_Tutorial;
	Texture_Array Settings_Label;
	Texture_Array Save_Settings;
	Texture_Array Tool;
	Texture_Array Help_Content;
	SDL_Texture* Recipe_Content;
	Texture_Array Door;
	SDL_Texture* Emblem;
	SDL_Texture* Crosshair;
	SDL_Texture* Cursor;
	SDL_Texture* Cursor_Core;
	SDL_Texture* Sapling;
	SDL_Texture* Node;
	SDL_Texture* Path_Arrow;
	SDL_Texture* Log_Background;
	SDL_Texture* Saveloader;
	SDL_Texture* R_Flash;
	Texture_Array A_Bubble;
	SDL_Texture* Floor_Texture;
	SDL_Texture* Frame_Texture;
	SDL_Texture* Tile_Texture;
	Texture_Array R_Pump;
	Texture2_Array Incinerator;
	Texture_Array RTG;
	Texture_Array F_Plant;
	Texture2_Array B_Generator;
	Texture2_Array Distillery;
	Texture2_Array G_Bed;
	Texture_Array C_Platform;
	Texture_Array B_Scrubber;
	SDL_Texture* MS_Controller;
	SDL_Texture* MS_Output;
	SDL_Texture* MS_Input;
	Texture_Array E_Plant;
	Texture2_Array F_Mixer;
	Texture_Array T_Tower;
	SDL_Texture* Flowerpot;
	Texture_Array A_Shelf;
	SDL_Texture* C_Node;
	Texture_Array G_Well;
	Texture_Array H_Exchanger;
	SDL_Texture* P_Wood;
	SDL_Texture* B_Tile;
	SDL_Texture* S_Carpet;
	SDL_Texture* H_Strip;
	SDL_Texture* M_Generator;
	SDL_Texture* F_Generator;
	Texture_Array R_Intersection;
	Texture_Array L_Intersection;
	Texture_Array SC_Input;
	Texture_Array SCH_Sink;
	Texture_Array SC_Transferor;
	Texture_Array SC_Output;
	Texture_Array ST_Input;
	Texture2_Array STIT_Block;
	Texture2_Array ST_Output;
	SDL_Texture* Scrap;
	SDL_Texture* Help_Sidebutton;
	SDL_Texture* Save_Sidebutton;
	SDL_Texture* Recipe_Sidebutton;
	SDL_Texture* Exit_Sidebutton;
	Texture_Array Submarine;
	Texture2_Array Confirmation;
	Texture_Array Pyramid;
	SDL_Texture* Mesh;
	Texture_Array Fire;
	Texture_Array None;
} lde_textures;

typedef struct {
	SDL_FRect Logo1;
	SDL_FRect Logo2;
	SDL_FRect Terminal_Prompt;
	SDL_FRect Price_Header;
	SDL_FRect CMD_Warning1;
	SDL_FRect CMD_Warning2;
	Rect3_Array Item_Labels;
	Rect3_Array Subcategories;
	Rect3_Array Subcontents;
	Rect2_Array New;
	Rect2_Array Load;
	Rect2_Array Clear;
	Rect2_Array Categories;
	Rect_Array Error_Exit;
	Rect2_Array MSP_Buttons;
	Rect2_Array SD_Buttons;
	Rect2_Array HX_Buttons;
	Rect2_Array MT_Buttons;
	Rect2_Array TT_Buttons;
	Rect_Array Tunnel;
	Rect_Array Return;
	Rect_Array New_Game;
	Rect_Array Settings;
	Rect_Array Update_Logs;
	Rect_Array Credits;
	Rect_Array Quit_Game;
	Rect_Array Apply;
	Rect_Array Cancel;
	Rect_Array Next_Day;
	Rect2_Array Anti_Aliasing;
	Rect2_Array V_Sync;
	Rect2_Array Sort;
	Rect2_Array TBW_Rectangle;
	Rect2_Array Tutorials;
	Rect_Array Tutorial_Hitbox;
	Rect2_Array Cheats;
	Rect_Array Clear_Tutorial;
	Rect_Array Settings_Label;
	Rect_Array Save_Settings;
	SDL_FRect Tool[LDE_TOOLS];
	SDL_FRect Help_Content[2];
	SDL_FRect Recipe_Content;
	SDL_FRect Door[2];
	SDL_FRect Emblem;
	SDL_FRect Tile_1x1;
	SDL_FRect Tile_1x2;
	SDL_FRect Tile_2x1;
	SDL_FRect Tile_2x2;
	SDL_FRect Tile_2x3;
	SDL_FRect Tile_3x2;
	SDL_FRect Tile_3x3;
	SDL_FRect Tile_3x4;
	SDL_FRect Tile_4x3;
	SDL_FRect Tile_4x6;
	SDL_FRect Tile_6x4;
	SDL_FRect Tile_6x8;
	SDL_FRect Tile_8x6;
	SDL_FRect Sapling;
	SDL_FRect Node;
	SDL_FRect R_Flash;
	SDL_FRect Log_Background;
	SDL_FRect Saveloader;
	SDL_FRect Help;
	SDL_FRect Save;
	SDL_FRect Recipe;
	SDL_FRect Exit;
	SDL_FRect Submarine;
	Rect2_Array Confirmation;
} lde_rects;

typedef struct {
	SDL_Color Abyss_Black;
	SDL_Color Pure_White;
	SDL_Color Light_Grey;
	SDL_Color Mid_Grey;
	SDL_Color Clean_Grey;
	SDL_Color Dark_Grey;
	SDL_Color Reinforced_Grey;
	SDL_Color Cherry_Blossom;
	SDL_Color Copper_Wire;
	SDL_Color Carnage_Pink;
	SDL_Color Hostile_Red;
	SDL_Color Ocean;
} lde_colors;

typedef struct {
	TTF_Font* Logo_Font;
	TTF_Font* Large_Font;
	TTF_Font* Text_Font;
	TTF_Font* Halftext_Font;
	TTF_Font* Subtext_Font;
	TTF_Font* Microtext_Font;
	TTF_Font* Terminal_Font;
} lde_fonts;

typedef struct {
	char* Keybind_Texts[LDE_KEYBINDS];
	SDL_Keycode Keybind_List[LDE_KEYBINDS];
	SDL_Keycode Keybind_Settings[LDE_KEYBINDS];
} lde_keybinds;

typedef struct {
	bool Settings_Changed;
	int Modular1_Requirement;
	int Modular2_Requirement;
	int Ticker_Target;
	int Ticker_Position;
	int Ticker_Frames;
	int Tutorial_Step;
	Point Tutorial_Size;
	Point Tutorial_Offset;
	int Temporary_FPS;
	float Scroll_Percent;
	bool Log_Inversions[3];
	Point First_Coordinate;
	Node_d Docks;
} lde_temporary;

typedef struct {
	int Wire_State;
	Texture_Array Wire_Cache;
	SDL_FRect Wire_Box;
	SDL_Texture* Blueprint_Cache;
	Texture2_Array Log_Cache;
	Rect2_Array Log_Rectangles;
	SDL_FRect Query[32];
	int ID_Query[32];
	SDL_Color Color_Query[32];
	int Query_Length;
	float* FPS_Cache;
	int FPS_Tick;
} lde_cache;

typedef struct {
	Texture_Supply FPS;
	Texture_Supply Scroll_Percent;
	Texture_Supply Changelog_Scroll;
	Texture_Supply Report_Header;
	Texture_Supply Monitor_Size;
	Texture_Supply Tutorial;
	Texture_Supply Subtutorial;
	Texture_Supply Money_Production;
	Texture_Supply Fluid_Production;
	Texture_Supply Shop1;
	Texture_Supply Shop2;
	Texture_Supply Shop3;
	Texture_Supply Shop4;
	Texture_Supply Shop5;
	Texture_Supply Money;
	Texture_Supply Time;
	Texture_Supply Save_Text;
	Texture_Supply Terminal_Title;
	Texture_Supply Terminal_Command;
	Texture_Supply Terminal_Logs[LDE_LOGMAX];
	Texture_Supply Catalog1[LDE_RECIPETYPES];
	Texture_Supply Catalog2[LDE_RECIPETYPES];
	Texture_Supply Catalog3[LDE_RECIPETYPES];
	Texture_Supply Filesizes[LDE_SAVEFILES];
} lde_supplies;

typedef struct {
	bool Locked;
	bool Building;
	bool Sprinting;
	bool Terminal_Clearing;
	float Ocean_Cycle;
	float Node_Cycle;
	float Movespeed;
	float Log_Offset;
	Point Tile;
	int Prompt_Identifier;
	int Subprompt_Identifier;
	int Tool;
	int UD_Input;
	int LR_Input;
	int Queried_Price;
	int Engagement;
	int UI_Tab;
	int Subtab;
	int UI_Selection;
	int Frame_Rate;
	int Time_Frames;
	int Max_Time_Frames;
	int Item;
	int Rotation;
	int Save_Frames;
	int Map_X;
	int Map_Y;
	int Registering_Keybind;
	int Slider_Positions[LDE_SLIDERS];
	SDL_FPoint Tile_Centerpoint;
	float Log_Heights[LDE_LOGS];
	int Valve300_Postions[LDE_VALVE300LENGTH];
	char Slider_Texts[LDE_SLIDERS][256][32];
	float Effects[LDE_EFFECTS];
	char Terminal_Logs[LDE_LOGMAX][128];
	char Terminal_Entry[128];
	int Terminal_Length;
	bool Bar_Up;
} lde_interface;

typedef struct {
	char JSON[LDE_JSONMAX][128];
	int Commands[LDE_CMDMAX];
	char Parameters[LDE_CMDMAX][4][128];
} lde_buffers;

typedef struct {
	Node EP_Inputs[4];
	Node EP_Outputs[4];
	Node FM_Inputs[4];
	Node FM_Outputs[4];
	Node BG_Inputs[4];
	Node I_Inputs[4];
	Node I_Outputs[4];
	Node D_Inputs[4];
	Node D_Outputs[4];
	Node STI_Inputs[4];
	Node GB_Outputs[4];
	Node STO_Outputs[4];
	Node GW_Inputs[4];
	Node GW_Outputs[4];
} lde_preconfigs;

extern lde_core Core;
extern lde_data Data;
extern lde_metadata Metadata;
extern lde_settings Settings;
extern lde_textures Textures;
extern lde_rects Rects;
extern lde_colors Colors;
extern lde_fonts Fonts;
extern lde_keybinds Keybinds;
extern lde_temporary Temporary;
extern lde_cache Cache;
extern lde_supplies Supplies;
extern lde_interface Interface;
extern lde_buffers Buffers;
extern lde_preconfigs Preconfigs;

void Preload_Fonts();
int Visual_To_ID(const int Identifier);
int Visual_To_Rotation(const int Identifier);
void ID_To_Size(const int ID, const int Rotation, int* W, int* H);
void Clear_Renderer();
void Set_Renderer_Color(const SDL_Color Color);
void Cleanup_Assets();
void Clear_File(const char* Path);
void Free_String2(String2* Target);
void Clear_Texture_Array(Texture_Array* Target);
void Clear_Texture2_Array(Texture2_Array* Target);
void Clear_Texture3_Array(Texture3_Array* Target);
void Clear_Rect2_Array(Rect2_Array* Target);
void Clear_Rect3_Array(Rect3_Array* Target);
int Get_Depth(float Number);
void Render_Outline(SDL_FRect Rectangle, SDL_Color Color, int Multiplier);
void Render_Box(int X, int Y, int W, int H, SDL_Color Inner_Color, SDL_Color Outer_Color);
void Render_Button(const Texture_Array* Button, const Rect_Array* Hitbox, int Selection, SDL_Color Underline_Color);
void Preload_Assets();
void Update_Tilestack(bool X_Lock, int X, bool Y_Lock, int Y);
bool Detect_Mouse_Collision(const SDL_FRect Target);
bool Compare_Colors(const SDL_Color Color1, const SDL_Color Color2);
void Generate_Preconfigs();
void Free_Preconfigs();
void Return_Nodes(Node* Yield, const int Column, const int Row, const int Rotation, Node Preconfig[4]);
bool Check_Clearance(const int X, const int Y, const int W, const int H);
void Fill_Clearance(const int Identifier, const int X, const int Y, const int W, const int H);
void Push_Docks(Point Input);
void Pull_Docks(int Position);
void Recache_TT_Commands();
void Preload_Terminal_Sidebar(const String2* Texts, Texture2_Array* Yield, Rect2_Array* Rectangles);
void Load_Button(TTF_Font* Font, const char* Text, Texture_Array* Yield, Rect_Array Rectangles,
	SDL_Color Color1, SDL_Color Color2);
SDL_FRect Buffer_Rectangle(const SDL_FRect Source, const int X, const int Y);
void Load_Modular(const char* Path, Texture_Array* Yield, int Size);
void Load_Rotational(const char* Path, Texture_Array* Yield);
void Load_Mirrored_Button(const char* Path, Texture2_Array* Yield, SDL_FRect* Rectangle);
void Load_Mirrored(const char* Path, Texture_Array* Yield,  SDL_FRect* Rectangle);
void Load_Animated(const char* Path, Texture_Array* Yield, int Height, bool Inverted, int* Rotationals);
void Load_Subanimated(const char* Path, Texture_Array* Yield, int Height);
void Load_Animated_Rotational(const char* Path, Texture2_Array* Yield, int Height, bool Inverted, int* Rotationals);
SDL_Texture* Preload_Sidebutton(const char* Path, SDL_FRect* Rectangle, float Y);
SDL_Texture* Preload_Texture(const char* Path);
void Abbreviate_Number(float Number, char* Buffer, int Size);
void Truncate(float Number, int Depth, char* Buffer, int Size);
int Render_Rich_Text(TTF_Font* Selected_Font, char* Raw_Text, int X, int Y, bool Inverted, bool Disabled);
void Render_Texture(SDL_Texture* Texture, SDL_FRect* Rect);
void Preload_Noise();
void Preclear_Temporaries();
void Render_Loadscreen();
void Tick_State();
void Reseed_State();