#pragma once
#include <core.h>
#include <prepping.h>
#include <grid.h>
#include <rendering.h>

extern char Errors[LDE_ERRORS][32];

void Render_Toolbar();
void Verify_Settings();
void Render_Tile_Prompts();
void Render_Interaction();
void Render_Effects();
void Cache_Blueprint();
void Cache_Price();
void Render_Daily_Report(Point Pos);
void Render_Help(Point Pos);
void Render_Shop(Point Pos);
void Render_Catalog(Point Pos);
void Render_Slider(char Labels[256][32], int Engagement, int Nodes, int Selection, int* Position, Point Pos, int Width,
	SDL_Color Primary, SDL_Color Secondary, bool Text_Visible);
void Render_Application();
void Render_Main();
void Render_Loader();
void Render_Settings();
void Render_Changelog();
void Render_Credits();
void Render_Backing();
void Render_Sidebuttons(Texture2_Array* Buttons, Rect2_Array* Hitboxes, UI_Link* Links);
void Print_Error(int Input);
void Print_Fatal_Error(int Input);
void Print_Response(const char* Response);
void Print_JSON();
void Print_Input();
void Forward_Essentials(int Buttons, int Sliders);
void Backward_Essentials();
void Render_Necessities(char* Machine, char* Prefix);
void Tick_Input(int Target, bool Slider);
void Return_Command(const int Type, const char* Parameters[]);
void Process_Commands();
void Render_Blueprint(int Size_X, int Size_Y);
void Render_Game_UI();
void Render_Saveloader();
void Render_Prompts();
void Drain_Query();
void Render_MSP_Controller(Point Pos);
void Render_T_Tower(Point Pos);
void Render_S_Dock(Point Pos);
void Render_H_Exchanger(Point Pos);
void Render_M_Generator(Point Pos);
void Render_F_Generator(Point Pos);
void Render_MT_Input(Point Pos);
void Render_P_Generator(Point Pos);
void Render_Hotbar();
void Back(Parameter Unused, Parameter Unused2);
void Swap_AA(Parameter Unused, Parameter Unused2);
void Quit(Parameter Unused, Parameter Unused2);
void Tab_Saveloader(Parameter Unused, Parameter Unused2);
void Switch_Tab(Parameter Tab, Parameter Unused);
void Update_Settings(Parameter Unused, Parameter Unused2);
void Invert_Changelog(Parameter Unused, Parameter Unused2);
void Jump_Changelog(Parameter Halfway, Parameter Unused);
void Swap_VS(Parameter Unused, Parameter Unused2);
void Clear_Configs(Parameter Unused, Parameter Unused2);
void Apply_Configs(Parameter Unused, Parameter Unused2);
void Spawn_Cheat(Parameter Type, Parameter Unused);
void Cancel_Tutorial(Parameter Unused, Parameter Unused2);
void CMD_Tutorial(Parameter Unused, Parameter Unused2);
void Gen_Tutorial(Parameter Unused, Parameter Unused2);
void Fish_Tutorial(Parameter Unused, Parameter Unused2);
void Apply_M_Cheat(Parameter Machine, Parameter Unused);
void Set_M_Cheat(Parameter Machine, Parameter Unused);
void Apply_P_Cheat(Parameter Machine, Parameter Unused);
void Set_F_Cheat(Parameter Machine, Parameter Unused);
void Apply_F_Cheat(Parameter Machine, Parameter Unused);
void Set_P_Cheat(Parameter Machine, Parameter Unused);
void Forward_Day(Parameter Unused, Parameter Unused2);
void Load_Save(Parameter Slot, Parameter Unused);
void Free_Save(Parameter Slot, Parameter Unused);
void New_Save(Parameter Slot, Parameter Unused);
void Machine_Exit(Parameter Unused, Parameter Unused2);
void HX_Diagnostics(Parameter Pos, Parameter Unused);
void MT_Diagnostics(Parameter Pos, Parameter Unused);
void SD_Link(Parameter Pos, Parameter Unused);
void SD_Manifest(Parameter Pos, Parameter Unused);
void SD_Drain(Parameter Pos, Parameter Tank);
void MSP_TInfo(Parameter Pos, Parameter Unused);
void MSP_FInfo(Parameter Pos, Parameter Unused);
void MSP_Fill(Parameter Pos, Parameter Unused);
void MSP_Empty(Parameter Pos, Parameter Unused);
void TT_Call_Sub(Parameter Dock, Parameter Unused);
void Shop_Category(Parameter Category, Parameter Unused);
void Shop_Item(Parameter Subcategory, Parameter Unused);
void Shop_Subcategory(Parameter Selection, Parameter Unused);
void Shop_Subitem(Parameter Selection, Parameter Unused);